### ISSUE TITLE
Update backend to support Sigma Filters

### ISSUE THREAD

**Issue by mostafa** [grafana/pySigma-backend-loki#159]
The recently released pySigma [v0.11.7](https://github.com/SigmaHQ/pySigma/releases/tag/v0.11.7) includes a feature known as Sigma Filters. Sigma Filters are a way to collect and apply false positives to Sigma rules and are based on the proposal discussed [here](https://github.com/SigmaHQ/sigma-specification/discussions/35).

**Comment by jamesc-grafana** [comment]
Related to #124
